// v2 ship archetypes (Task 4.1) — 4 ships with distinct stats + projectile types
export const SHIPS = {
  vanguard: {
      id: 'vanguard',
      name: 'GUNNER',
      desc: 'Dual-wield rapid-fire, high fire rate',
      color: '#ff6b35',
      hp: 4000,
      speed: 300,
      fireRate: 0.08,
      damage: 0.85,
      projectile: 'twin',
      unlockCost: 0,
      unlocked: true,
    },
    interceptor: {
      id: 'interceptor',
      name: 'INTERCEPTOR',
      desc: 'Standard single-shot blaster, base weapon',
      color: '#4a9eff',
      hp: 4000,
      speed: 280,
      fireRate: 0.14,
      damage: 0.85,
      projectile: 'single',
      unlockCost: 500,
      unlocked: false,
    },
  pulsar: {
    id: 'pulsar',
    name: 'PULSAR',
    desc: 'Slow pulse cannon, high damage',
    color: '#ffeb3b',
    hp: 5000,
    speed: 240,
    fireRate: 0.22,
    damage: 1.5,
    projectile: 'pulse',
    weapon: 'plasma',
    unlockCost: 800,
    unlocked: false,
  },
  juggernaut: {
    id: 'juggernaut',
    name: 'JUGGERNAUT',
    desc: 'Tank. Highest HP + raw damage',
    color: '#00e676',
    hp: 7000,
    speed: 200,
    fireRate: 0.28,
    damage: 2.2,
    projectile: 'single',
    weapon: 'lance',
    unlockCost: 1200,
    unlocked: false,
  },
};